name: Build XCFramework CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Fetch base SHA
        run: git fetch --depth=1 origin ${{ github.event.pull_request.base.sha }}

      - id: check
        shell: bash
        run: |
          DIFF=$(git diff --name-only FETCH_HEAD ${{ github.event.pull_request.head.sha }})

          # Keep changes in multiplatform-authenticator or Core submodule updates or this workflow file
          CHANGES=$(echo "$DIFF" | grep -E '^(multiplatform-authenticator($|/)|Core($|/)|\.github/workflows/build-xcframework\.yml$)' || true)
          
          if [ -z "$CHANGES" ]; then
            echo "No relevant changes found. Skipping tests."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "Relevant changes detected."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  build-apple-bundle:
    name: Verify generation of XCframework
    needs: check-changes
      # This job ONLY runs if the previous job found relevant files
    if: needs.check-changes.outputs.should_run == 'true'
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.3
        with:
          token: ${{ github.token }}
          submodules: recursive

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
        with:
          cache-provider: basic

      # Making sure XCFramework build
      - name: Build XCFramework
        run: ./gradlew :AuthenticatorCore:assembleCoreAuthenticatorXCFramework
